/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentación;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *Frame principal que muesta el menu inicial con las opciones de iniciar partida
 * o unirse a una nueva. 
 * @author Carlos A. Valle Encinas - David Sotelo Palafox. Equipo #6
 */
public class MenuPrincipal extends javax.swing.JFrame {
Fondo fondo=new Fondo();
    
    /**
     * Constructor del Menu Principal.
     */
    public MenuPrincipal() 
    { 
        this.setContentPane(fondo);  
        initComponents();
        tamañoPlay();
        tamañoUnirse();
    }
    
/**
*Método que permite ajustar el tamaño del icono "jugar" ubicado en el paquete
*img.
*/
public void tamañoPlay() 
    {
        ImageIcon play;
        play = new ImageIcon(getClass().getResource("/img/play.png"));
        Icon png = new ImageIcon(play.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        muestraPantallaIniciarPartida.setIcon(png);
    }

/**
*Método que permite ajustar el tamaño del icono "unirse" ubicado en el paquete
*img. 
*/
    public void tamañoUnirse() {
        ImageIcon uni;
        uni = new ImageIcon(getClass().getResource("/img/unirse.png"));
        Icon png = new ImageIcon(uni.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        menuUnirsePartida.setIcon(png);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        muestraPantallaIniciarPartida = new javax.swing.JButton();
        menuUnirsePartida = new javax.swing.JButton();
        btnSalirJuego = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAcercaDe = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patolli");

        muestraPantallaIniciarPartida.setBackground(new java.awt.Color(204, 255, 255));
        muestraPantallaIniciarPartida.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        muestraPantallaIniciarPartida.setForeground(new java.awt.Color(102, 51, 0));
        muestraPantallaIniciarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        muestraPantallaIniciarPartida.setText("Iniciar Partida");
        muestraPantallaIniciarPartida.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        muestraPantallaIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muestraPantallaIniciarPartidaActionPerformed(evt);
            }
        });

        menuUnirsePartida.setBackground(new java.awt.Color(204, 255, 255));
        menuUnirsePartida.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        menuUnirsePartida.setForeground(new java.awt.Color(102, 51, 0));
        menuUnirsePartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unirse.png"))); // NOI18N
        menuUnirsePartida.setText("Unirse a Partida");
        menuUnirsePartida.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        menuUnirsePartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnirsePartidaActionPerformed(evt);
            }
        });

        btnSalirJuego.setBackground(new java.awt.Color(204, 255, 255));
        btnSalirJuego.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnSalirJuego.setForeground(new java.awt.Color(102, 51, 0));
        btnSalirJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log_out.png"))); // NOI18N
        btnSalirJuego.setText("Salir del Juego");
        btnSalirJuego.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSalirJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirJuegoActionPerformed(evt);
            }
        });

        menuAcercaDe.setText("Acerca De");

        menuInfo.setText("Info.");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });
        menuAcercaDe.add(menuInfo);

        jMenuBar1.add(menuAcercaDe);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuUnirsePartida, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(muestraPantallaIniciarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalirJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muestraPantallaIniciarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuUnirsePartida, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalirJuego)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

/**
*Método oyente que muesta la pantalla de menu iniciar partida. 
*@param evt: evento al que escucha. 
*/
    private void muestraPantallaIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muestraPantallaIniciarPartidaActionPerformed
        // TODO add your handling code here:
       MenuIniciaPartida iniciar=new MenuIniciaPartida();
       iniciar.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_muestraPantallaIniciarPartidaActionPerformed

/**
*Método oyente que cierra el frame de menu principal. 
*@param evt: evento al que escucha. 
*/
    private void btnSalirJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirJuegoActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_btnSalirJuegoActionPerformed

/**
*Método oyente que muestra información acerca de los participantes del proyecto
*mediante un JOptionPane. 
* @param evt: Evento al que escucha. 
*/
    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Proyecto Final Arquitectura de Software\n" + 
        "\n\n Carlos Arturo Valle Encinas \n" + "\n\n David Sotelo Palafox \n" + "\n\n Equipo #6 \n", 
        "Acerca de", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuInfoActionPerformed

/**
*Método oyente que muestra la pantalla de menu Unirse a Partida. 
* @param evt: Evento al que escucha. 
*/
    private void menuUnirsePartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnirsePartidaActionPerformed
        // TODO add your handling code here:
        MenuUnirsePartida unirse=new MenuUnirsePartida();
        unirse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuUnirsePartidaActionPerformed

    /**
     *Método main que ejecuta el frame de menu principal. 
     * @param args argumento de lineas de comando.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenuItem menuInfo;
    private javax.swing.JButton menuUnirsePartida;
    private javax.swing.JButton muestraPantallaIniciarPartida;
    // End of variables declaration//GEN-END:variables

}

